@startuml

actor "UI"

"UI"-> FluxoCaixa: Registrar(movimento)
"FluxoCaixa"-> EventBus: EnviarComando(MovimentoCommand)
"EventBus"-> Registro: Salvar(MovimentoCommand)
"EventBus" <- Registro: PublicarEvento(MovimentoRegistradoEvent)
"EventBus" <- Registro: Confirma registro do lançamento
"FluxoCaixa" <-- EventBus: Confirma registro do lançamento
"UI" <-- FluxoCaixa: Confirma registro do lançamento

"EventBus" -> Consolidador: 
"Consolidador" -> Consolidador: Consolida lançamento
"Consolidador" -> Cache : Persistir(consolidado)
"Consolidador" <-- Cache : OK

@enduml