// <auto-generated />
using System;
using Fcx.Caixa.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fcx.Caixa.Infrastructure.Migrations
{
    [DbContext(typeof(MovimentoContext))]
    partial class MovimentoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fcx.Caixa.Domain.Lancamento", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("CodigoLancamento")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime");

                    b.Property<string>("Finalidade")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TipoDC")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("Identificador");

                    b.ToTable("Lancamento", (string)null);
                });

            modelBuilder.Entity("Fcx.Caixa.Domain.Movimento", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("datetime");

                    b.Property<Guid>("LancamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Identificador");

                    b.HasIndex("LancamentoId");

                    b.ToTable("Movimento", (string)null);
                });

            modelBuilder.Entity("Fcx.Caixa.Domain.Movimento", b =>
                {
                    b.HasOne("Fcx.Caixa.Domain.Lancamento", "Lancamento")
                        .WithMany("Movimento")
                        .HasForeignKey("LancamentoId")
                        .IsRequired();

                    b.Navigation("Lancamento");
                });

            modelBuilder.Entity("Fcx.Caixa.Domain.Lancamento", b =>
                {
                    b.Navigation("Movimento");
                });
#pragma warning restore 612, 618
        }
    }
}
